/* User Action Types */
export const HANDLE_USER = 'HANDLE_USER'
export const HANDLE_SAVE_DATA_USER = 'HANDLE_SAVE_DATA_USER'
export const HANDLE_CLEAR_DATA_USER = 'HANDLE_CLEAR_DATA_USER'

/* Common Action Types */
export const HANDLE_STEPPER = 'HANDLE_STEPPER'
export const HANDLE_UTIL_ALERT = 'HANDLE_UTIL_ALERT'
export const HANDLE_UTIL_DIALOG = 'HANDLE_UTIL_DIALOG'
export const HANDLE_SELECTED_THEME = 'HANDLE_SELECTED_THEME'
